### ISSUE TITLE
db.tab.h

### ISSUE THREAD

**Issue by nana88** [aitjcize/QCamber#10]
Hello,

Could I ask, where is db.tab.h? I could not build the project because of this missing file...

Yours sincerely,
Nana

**Comment by aitjcize** [comment]
Take a look at:
https://github.com/aitjcize/QCamber/blob/master/src/parser/odbpp/odbpp.pri

This project file includes `flex.pri` and `bison.pri` which are part of the Qt project to provide lex & yacc compilation support. The `db.tab.h` is generated by it.
