### ISSUE TITLE
Is this a typo or something?

### ISSUE THREAD

**Issue by yodalee** [aitjcize/QCamber#9]
https://github.com/aitjcize/QCamber/blob/master/src/parser/odbpp/featuresparser.cpp#L80
Is that `&&` correct? Since this will not ignore empty line.

**Comment by aitjcize** [comment]
yes ... feel free to fix it.

**Comment by aitjcize** [comment]
fixed.

**Comment by yodalee** [comment]
[![LGTM](http://lgtm.in/p/ajz7H6Qoq)](http://lgtm.in/i/ajz7H6Qoq)
